/**
 * Project Command Center — data source.
 *
 * This file powers the entire dashboard. Future AI agents (and humans) should
 * edit THIS file to keep the Command Center accurate — the page renders from it.
 *
 * It is intentionally a plain JS global (not a fetched JSON file) so the page
 * works both when opened directly (file://) and when served from GitHub Pages,
 * with no build step and no local server.
 *
 * This is example data for a fictional product, "Forkcast", to demonstrate the
 * Command Center prompt. Replace it with your real project's data.
 */
window.COMMAND_CENTER_DATA = {
  projectOverview: {
    name: "Forkcast",
    description: "An AI meal-planning copilot that turns your pantry, diet, and budget into a week of recipes and an auto-built grocery order.",
    phase: "MVP Build",
    status: "in-progress",
    targetUsers: "Busy home cooks (25–45) who want healthy, budget-aware weekly meal plans without the planning overhead.",
    valueProposition: "From 'what's for dinner?' to a full week of personalized recipes + a one-tap grocery order in under 60 seconds.",
    lastUpdated: "2026-06-06",
    currentMilestone: "M3 — Closed Beta",
    version: "0.4.0",
  },

  roadmap: [
    {
      id: "r1",
      title: "Discovery & Research",
      description: "User interviews, competitor teardown, and demand validation.",
      status: "done",
      progress: 100,
      priority: "high",
      relatedFiles: ["docs/research/interviews.md", "docs/research/market.md"],
      notes: ["18 interviews completed", "Top pain: decision fatigue, not cooking skill"],
    },
    {
      id: "r2",
      title: "PRD & Requirements",
      description: "Product requirements for the core planning loop and grocery export.",
      status: "done",
      progress: 100,
      priority: "high",
      relatedFiles: ["docs/prd/core-planning.md"],
      notes: ["Approved 2026-03-12"],
    },
    {
      id: "r3",
      title: "Design System",
      description: "Component library, tokens, and the plan-builder UX.",
      status: "done",
      progress: 100,
      priority: "medium",
      relatedFiles: ["src/ui/tokens.css", "docs/design/figma-link.md"],
      notes: ["Dark + light themes shipped"],
    },
    {
      id: "r4",
      title: "Core Architecture",
      description: "Auth, data model, LLM orchestration, and the recipe/grocery services.",
      status: "done",
      progress: 100,
      priority: "high",
      relatedFiles: ["src/server/", "src/lib/llm/"],
      notes: ["Postgres + edge functions", "LLM calls routed through a cost-guarded gateway"],
    },
    {
      id: "r5",
      title: "MVP Build",
      description: "Plan generation, pantry input, grocery list, and account basics.",
      status: "in-progress",
      progress: 65,
      priority: "high",
      relatedFiles: ["src/features/planner/", "src/features/grocery/"],
      notes: ["Planner + grocery list working", "Pantry sync in progress"],
    },
    {
      id: "r6",
      title: "Grocery Integrations",
      description: "One-tap checkout via Instacart and Amazon Fresh.",
      status: "blocked",
      progress: 20,
      priority: "high",
      relatedFiles: ["src/integrations/instacart/"],
      notes: ["Blocked on Instacart partner API approval"],
    },
    {
      id: "r7",
      title: "Closed Beta",
      description: "Invite 200 users, instrument retention, gather feedback.",
      status: "in-progress",
      progress: 30,
      priority: "high",
      relatedFiles: ["docs/beta/plan.md"],
      notes: ["62/200 invites accepted"],
    },
    {
      id: "r8",
      title: "Testing & Hardening",
      description: "E2E coverage, allergen-safety validation, load testing.",
      status: "needs-review",
      progress: 25,
      priority: "high",
      relatedFiles: ["tests/"],
      notes: ["Allergen filtering needs a dedicated test suite — see risks"],
    },
    {
      id: "r9",
      title: "Public Launch",
      description: "Pricing, marketing site, App Store submission.",
      status: "not-started",
      progress: 0,
      priority: "medium",
      relatedFiles: [],
      notes: ["Target Q4 2026"],
    },
  ],

  features: [
    {
      id: "f1",
      name: "AI Weekly Plan Generator",
      area: "Planning",
      description: "Generates a 7-day plan from diet, budget, household size, and pantry.",
      status: "done",
      priority: "high",
      progress: 95,
      relatedFiles: ["src/features/planner/generate.ts", "src/lib/llm/planPrompt.ts"],
      testStatus: "partial",
      owner: "AI",
      notes: ["Median generation time 11s", "Streaming UI in place"],
    },
    {
      id: "f2",
      name: "Pantry Tracking",
      area: "Planning",
      description: "Track what you have so plans reuse ingredients and cut waste.",
      status: "in-progress",
      priority: "high",
      progress: 55,
      relatedFiles: ["src/features/pantry/"],
      testStatus: "missing",
      owner: "Human",
      notes: ["Manual add works", "Barcode scan not started"],
    },
    {
      id: "f3",
      name: "Smart Grocery List",
      area: "Grocery",
      description: "Aggregates plan ingredients into an organized, de-duplicated list.",
      status: "done",
      priority: "high",
      progress: 90,
      relatedFiles: ["src/features/grocery/list.ts"],
      testStatus: "covered",
      owner: "AI",
      notes: ["Groups by store aisle"],
    },
    {
      id: "f4",
      name: "One-Tap Checkout",
      area: "Grocery",
      description: "Send the list straight to Instacart / Amazon Fresh.",
      status: "blocked",
      priority: "high",
      progress: 20,
      relatedFiles: ["src/integrations/instacart/"],
      testStatus: "missing",
      owner: "Human",
      notes: ["Awaiting partner API access"],
    },
    {
      id: "f5",
      name: "Allergen & Diet Guardrails",
      area: "Safety",
      description: "Hard filters to exclude allergens and honor dietary restrictions.",
      status: "needs-review",
      priority: "high",
      progress: 60,
      relatedFiles: ["src/lib/safety/allergens.ts"],
      testStatus: "partial",
      owner: "Human",
      notes: ["Critical safety path — see high-severity risk"],
    },
    {
      id: "f6",
      name: "Recipe Detail & Steps",
      area: "Planning",
      description: "Full recipe view with scaled quantities and cook mode.",
      status: "done",
      priority: "medium",
      progress: 100,
      relatedFiles: ["src/features/recipe/"],
      testStatus: "covered",
      owner: "AI",
      notes: [],
    },
    {
      id: "f7",
      name: "Budget Estimator",
      area: "Planning",
      description: "Estimates weekly cost from regional price data.",
      status: "in-progress",
      priority: "medium",
      progress: 40,
      relatedFiles: ["src/features/budget/"],
      testStatus: "missing",
      owner: "AI",
      notes: ["Price data only covers US for now"],
    },
    {
      id: "f8",
      name: "Accounts & Sync",
      area: "Platform",
      description: "Auth, profiles, and cross-device sync of plans.",
      status: "done",
      priority: "high",
      progress: 100,
      relatedFiles: ["src/server/auth/"],
      testStatus: "covered",
      owner: "Human",
      notes: ["Magic-link auth"],
    },
  ],

  currentFocus: {
    activeMilestone: "M3 — Closed Beta",
    inProgress: [
      "Pantry barcode scanning",
      "Budget estimator accuracy pass",
      "Beta onboarding flow polish",
    ],
    nextActions: [
      "Write the allergen-safety test suite (highest priority)",
      "Unblock Instacart integration or ship a CSV/print fallback",
      "Instrument week-2 retention for beta cohort",
    ],
    pendingReview: [
      "Allergen guardrails implementation (f5)",
      "Testing & hardening roadmap item (r8)",
    ],
    blockers: [
      "Instacart partner API approval pending (blocks f4 + r6)",
    ],
  },

  architecture: {
    summary: "A Next.js web client talks to edge API routes. An LLM gateway wraps the model with cost + safety guards. Postgres stores users, plans, and pantry; Redis caches recipe generations. Grocery checkout is delegated to third-party partner APIs.",
    components: [
      { name: "Web Client", type: "frontend", description: "Next.js App Router UI, plan builder, recipe views.", relatedFiles: ["src/app/", "src/features/"] },
      { name: "Edge API", type: "backend", description: "Route handlers for plans, pantry, grocery, auth.", relatedFiles: ["src/server/"] },
      { name: "LLM Gateway", type: "ai", description: "Wraps the model with prompt templates, cost caps, and safety filters.", relatedFiles: ["src/lib/llm/"] },
      { name: "Postgres", type: "database", description: "Users, plans, pantry items, recipes.", relatedFiles: ["src/server/db/schema.sql"] },
      { name: "Redis Cache", type: "database", description: "Caches generated plans to cut LLM cost.", relatedFiles: ["src/lib/cache/"] },
      { name: "Auth (Magic Link)", type: "service", description: "Passwordless email auth.", relatedFiles: ["src/server/auth/"] },
      { name: "Grocery Partners", type: "external", description: "Instacart / Amazon Fresh checkout APIs.", relatedFiles: ["src/integrations/"] },
    ],
    dataFlows: [
      "User input → Edge API → LLM Gateway → plan JSON → Postgres + Redis → Web Client",
      "Plan → Grocery service → aggregated list → Partner API → order",
    ],
    externalServices: ["OpenAI/Anthropic (via gateway)", "Instacart Partner API", "Amazon Fresh API", "Resend (email)", "Stripe (planned)"],
  },

  prdTracker: [
    {
      id: "prd1",
      title: "Core Planning Loop",
      status: "implemented",
      summary: "Generate, edit, and save a personalized weekly meal plan.",
      coveredRequirements: ["Diet/budget inputs", "7-day generation", "Edit & regenerate", "Save & sync"],
      missingRequirements: ["Leftover-aware planning"],
      openQuestions: ["Should regeneration preserve user edits by default?"],
      relatedFiles: ["docs/prd/core-planning.md", "src/features/planner/"],
    },
    {
      id: "prd2",
      title: "Grocery Export & Checkout",
      status: "in-progress",
      summary: "Turn a plan into an organized list and a real grocery order.",
      coveredRequirements: ["List aggregation", "Aisle grouping"],
      missingRequirements: ["Partner checkout", "Price-aware substitutions"],
      openQuestions: ["Which partner to launch with first?"],
      relatedFiles: ["docs/prd/grocery.md", "src/features/grocery/"],
    },
    {
      id: "prd3",
      title: "Safety & Dietary Guardrails",
      status: "needs-review",
      summary: "Guarantee allergen and dietary exclusions are never violated.",
      coveredRequirements: ["Allergen exclusion filter", "Vegan/veg/keto presets"],
      missingRequirements: ["Cross-contamination warnings", "Verified ingredient allergen DB"],
      openQuestions: ["Do we need legal review before public launch?"],
      relatedFiles: ["src/lib/safety/allergens.ts"],
    },
    {
      id: "prd4",
      title: "Monetization",
      status: "draft",
      summary: "Subscription tiers and billing.",
      coveredRequirements: [],
      missingRequirements: ["Pricing model", "Stripe integration", "Paywall UX"],
      openQuestions: ["Freemium vs free-trial?"],
      relatedFiles: [],
    },
  ],

  decisions: [
    {
      date: "2026-02-20",
      title: "Route all model calls through an LLM gateway",
      decision: "Wrap the model behind an internal gateway with caching and per-user cost caps.",
      rationale: "Uncapped LLM spend was the top financial risk; caching identical plans cuts cost ~40%.",
      impact: "Predictable unit economics; one place to swap models or add safety filters.",
      relatedFiles: ["src/lib/llm/"],
    },
    {
      date: "2026-03-12",
      title: "Ship grocery LIST before grocery CHECKOUT",
      decision: "Decouple list generation from partner checkout and ship the list first.",
      rationale: "Partner API approvals are slow and out of our control; the list alone is already useful.",
      impact: "Beta can launch without blocking on integrations.",
      relatedFiles: ["src/features/grocery/"],
    },
    {
      date: "2026-04-01",
      title: "Magic-link auth over passwords",
      decision: "Use passwordless email auth.",
      rationale: "Lower friction for the target audience; no password storage liability.",
      impact: "Email deliverability becomes a dependency.",
      relatedFiles: ["src/server/auth/"],
    },
    {
      date: "2026-05-15",
      title: "Treat allergen filtering as a hard safety boundary",
      decision: "Allergen exclusions are enforced in code post-generation, never trusted to the model alone.",
      rationale: "A model hallucinating a safe-but-not ingredient is a real-world health risk.",
      impact: "Requires a verified ingredient/allergen dataset and dedicated tests.",
      relatedFiles: ["src/lib/safety/allergens.ts"],
    },
  ],

  risks: [
    {
      id: "risk1",
      type: "risk",
      severity: "high",
      title: "Allergen filtering not fully tested",
      description: "Allergen guardrails exist but lack a dedicated test suite. A miss could cause a real allergic reaction.",
      suggestedAction: "Build an allergen-safety test suite with known-adversarial cases before any public launch.",
      relatedFiles: ["src/lib/safety/allergens.ts", "tests/"],
    },
    {
      id: "risk2",
      type: "blocker",
      severity: "high",
      title: "Instacart partner API approval pending",
      description: "One-tap checkout and the grocery-integration roadmap item are blocked on external approval.",
      suggestedAction: "Pursue Amazon Fresh in parallel; ship a CSV/print fallback so the feature degrades gracefully.",
      relatedFiles: ["src/integrations/instacart/"],
    },
    {
      id: "risk3",
      type: "tech-debt",
      severity: "medium",
      title: "Pantry feature has no tests",
      description: "Pantry tracking is shipping without automated coverage.",
      suggestedAction: "Add unit + integration tests as the feature stabilizes.",
      relatedFiles: ["src/features/pantry/"],
    },
    {
      id: "risk4",
      type: "open-question",
      severity: "medium",
      title: "Budget data is US-only",
      description: "Price estimates aren't valid outside the US, limiting international beta.",
      suggestedAction: "Decide whether to source international price data or geo-gate the feature.",
      relatedFiles: ["src/features/budget/"],
    },
    {
      id: "risk5",
      type: "risk",
      severity: "low",
      title: "Email deliverability dependency",
      description: "Magic-link auth means a deliverability issue blocks all logins.",
      suggestedAction: "Monitor bounce rates; keep a backup provider configured.",
      relatedFiles: ["src/server/auth/"],
    },
  ],

  agentNotes: {
    quickStart: [
      "Read docs/prd/core-planning.md for the product's heart: the weekly planning loop.",
      "The LLM gateway (src/lib/llm/) is the cost + safety chokepoint — understand it before touching generation.",
      "Allergen filtering is a hard safety boundary; never weaken it for convenience.",
    ],
    importantFiles: [
      "src/features/planner/generate.ts — plan generation entry point",
      "src/lib/llm/ — model gateway, prompts, cost caps",
      "src/lib/safety/allergens.ts — safety-critical filtering",
      "src/features/grocery/list.ts — grocery aggregation",
    ],
    commands: [
      "pnpm dev — run locally",
      "pnpm test — run the test suite",
      "pnpm lint && pnpm typecheck — pre-commit checks",
      "pnpm build — production build",
    ],
    conventions: [
      "Features live under src/features/<name>/ with co-located tests.",
      "All model calls go through the gateway — never call the model SDK directly.",
      "Server-only code stays under src/server/.",
    ],
    pitfalls: [
      "Don't trust the model for allergen safety — always enforce in code.",
      "Don't call the LLM without going through the cost-guarded gateway.",
      "Plans are cached in Redis; invalidate when the prompt template changes.",
    ],
    nextRecommendedTasks: [
      "Write the allergen-safety test suite (highest priority).",
      "Add a CSV/print grocery fallback to unblock checkout value.",
      "Add pantry tests before barcode scanning lands.",
    ],
  },

  changelog: [
    { date: "2026-06-06", type: "doc", title: "Command Center created", description: "Added the living project dashboard.", relatedFiles: ["example/"] },
    { date: "2026-06-04", type: "feature", title: "Smart grocery list ships", description: "Aisle-grouped, de-duplicated list from any plan.", relatedFiles: ["src/features/grocery/list.ts"] },
    { date: "2026-05-28", type: "feature", title: "Pantry manual entry", description: "Users can add pantry items so plans reuse ingredients.", relatedFiles: ["src/features/pantry/"] },
    { date: "2026-05-15", type: "decision", title: "Allergen filtering is a hard boundary", description: "Enforced in code, never trusted to the model.", relatedFiles: ["src/lib/safety/allergens.ts"] },
    { date: "2026-05-02", type: "risk", title: "Instacart approval delay flagged", description: "Checkout integration blocked on external approval.", relatedFiles: ["src/integrations/instacart/"] },
    { date: "2026-04-18", type: "feature", title: "Streaming plan generation", description: "Plans now stream into the UI as they generate.", relatedFiles: ["src/features/planner/generate.ts"] },
    { date: "2026-04-01", type: "setup", title: "Magic-link auth", description: "Replaced password auth with passwordless email.", relatedFiles: ["src/server/auth/"] },
  ],

  humanActions: [
    {
      id: "ha1",
      priority: "critical",
      title: "Acquire a verified allergen-ingredient database license",
      description: "Our allergen guardrails currently rely on a manually curated list. For public launch, we need a licensed, continuously updated ingredient/allergen dataset (e.g. Open Food Facts premium, Edamam, or Spoonacular) to guarantee accuracy.",
      blocks: ["Public launch", "PRD3 — Safety & Dietary Guardrails", "Allergen safety test suite (needs a trustworthy ground-truth dataset)"],
      howTo: "Evaluate Edamam Food Database API (edamam.com), Spoonacular (spoonacular.com/food-api), and Open Food Facts. Request pricing and a sample dataset. Sign up and obtain API credentials.",
      assignedTo: "Founder",
      dueBy: "Before any public launch or press coverage",
      status: "pending",
    },
    {
      id: "ha2",
      priority: "critical",
      title: "Follow up on Instacart Partner API application",
      description: "The one-tap grocery checkout feature is fully blocked on Instacart granting partner API access. The application was submitted 2026-05-02 and has had no response.",
      blocks: ["Feature: One-Tap Checkout", "Roadmap: Grocery Integrations (r6)"],
      howTo: "Email the Instacart developer partnerships team at partnerships@instacart.com referencing your application ID. In parallel, start the Amazon Fresh Partner API application at developer.amazon.com/apps-and-games/amazon-fresh.",
      assignedTo: "Founder / BD",
      dueBy: "This week — the delay is compounding",
      status: "pending",
    },
    {
      id: "ha3",
      priority: "high",
      title: "Legal review: allergen safety claims and liability exposure",
      description: "Before Forkcast goes public, a lawyer familiar with food-tech needs to review the allergen filtering approach, any in-app safety claims, and our ToS. A missed allergen is a real-world health risk and a litigation risk.",
      blocks: ["Public launch", "Marketing site copy", "App Store submission"],
      howTo: "Engage a food-tech or consumer-product lawyer. Start with Clerky or a local firm. Share the allergen filtering code, the safety PRD, and the draft ToS. Ask specifically about disclaimer language and liability caps.",
      assignedTo: "Founder",
      dueBy: "8 weeks before target public launch",
      status: "pending",
    },
    {
      id: "ha4",
      priority: "high",
      title: "Set up Stripe account and configure products/webhooks",
      description: "Monetization is a draft PRD. To unblock any subscription billing work, a real Stripe account needs to exist with products, prices, and webhook endpoints configured.",
      blocks: ["PRD4 — Monetization", "Stripe integration dev work"],
      howTo: "Go to stripe.com, create an account under the company entity. Create a Product named 'Forkcast Pro', add a recurring monthly price ($9.99) and an annual price ($89). Copy the webhook signing secret into the .env. Share publishable + secret keys with the dev.",
      assignedTo: "Founder",
      dueBy: "Before sprint starts on Monetization PRD",
      status: "pending",
    },
  ],

  nextSteps: [
    {
      order: 1,
      title: "Write allergen-safety test suite",
      description: "Build a dedicated test suite with known-adversarial cases (e.g. peanut in a 'nut-free' plan) to verify the guardrails catch every exclusion. This is the single highest-risk gap before launch.",
      owner: "AI",
      effort: "medium",
      unlocks: "Public launch confidence, PRD3 completion, ability to make safety claims in marketing",
      blockedBy: "ha1",
    },
    {
      order: 2,
      title: "Follow up on Instacart API / start Amazon Fresh application",
      description: "The checkout integration has been blocked for 5 weeks. Either get Instacart to respond or start Amazon Fresh in parallel this week.",
      owner: "Human",
      effort: "small",
      unlocks: "Grocery integration roadmap item, One-tap checkout feature",
      blockedBy: "",
    },
    {
      order: 3,
      title: "Build CSV/print grocery list fallback",
      description: "Decouple checkout value from the partner API dependency. Let users export their grocery list as CSV or a print-friendly view today, regardless of Instacart status.",
      owner: "AI",
      effort: "small",
      unlocks: "Grocery value for beta users now; reduces pressure on Instacart timeline",
      blockedBy: "",
    },
    {
      order: 4,
      title: "License allergen-ingredient database",
      description: "Evaluate and sign up for a verified ingredient/allergen API so safety guardrails are grounded in a trustworthy dataset.",
      owner: "Human",
      effort: "small",
      unlocks: "Allergen test suite (step 1), legal sign-off, public launch",
      blockedBy: "",
    },
    {
      order: 5,
      title: "Add pantry tests before barcode scanning lands",
      description: "Pantry manual entry shipped without tests. Add unit and integration coverage before the barcode scanning feature adds more complexity.",
      owner: "AI",
      effort: "small",
      unlocks: "Confidence to ship barcode scanning; closes tech-debt risk",
      blockedBy: "",
    },
    {
      order: 6,
      title: "Instrument week-2 beta retention",
      description: "Track whether users return for a second week of meal planning. This is the key signal for product-market fit at current stage.",
      owner: "AI",
      effort: "medium",
      unlocks: "Data-driven iteration decisions for post-beta roadmap",
      blockedBy: "",
    },
  ],
};
